spring:
  profiles:
    active: dev
  config:
    import: consul:localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
  application:
    name: sample-app-consul-config
jasypt:
  encryptor:
    bean: encryptorBean
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  health:
    defaults:
      enabled: true
  info:
    defaults:
      enabled: true
    git:
      mode: full